# Generated by Django 3.2 on 2022-05-03 17:06

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник')),
                ('episodes', models.IntegerField(default=0, verbose_name='Количество эпизодов')),
                ('score', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'Онгоинг'), ('RELEASED', 'Выпущено')], max_length=255, verbose_name='Статус')),
                ('synopsis', models.TextField(blank=True, verbose_name='Синопсис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/genre/', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('image', models.ImageField(null=True, upload_to='anime/', validators=[api.utils.validate_size, api.utils.validate_extension], verbose_name='Изображение')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='api.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'ImИзображения',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anime', to='api.genre', verbose_name='Жанр'),
        ),
    ]
