# Generated by Django 3.2 on 2022-05-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='api.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.CharField(blank=True, choices=[('MANGA', 'Манга'), ('LIGHT_NOVEL', 'Лайт новелла')], max_length=255, null=True, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('volumes', models.IntegerField(default=0, verbose_name='Количество томов')),
                ('chapters', models.IntegerField(default=0, verbose_name='Количество глав')),
                ('score', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('status', models.CharField(blank=True, choices=[('ONGOING', 'Онгоинг'), ('RELEASED', 'Выпущено')], max_length=255, verbose_name='Статус')),
                ('synopsis', models.TextField(blank=True, verbose_name='Синопсис')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
            },
        ),
    ]
