# Generated by Django 3.2 on 2022-05-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220504_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='light_novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='light_novel_images', to='api.lightnovel', verbose_name='Ранобэ'),
        ),
        migrations.AddField(
            model_name='image',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manga_images', to='api.manga', verbose_name='Манга'),
        ),
        migrations.AlterField(
            model_name='image',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anime_images', to='api.anime', verbose_name='Аниме'),
        ),
    ]
