# Generated by Django 3.2 on 2022-05-04 10:06

import api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20220504_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[api.utils.validate_size, api.utils.validate_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='light_novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='light_novel_images', to='api.lightnovel', verbose_name='Ранобэ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manga_images', to='api.manga', verbose_name='Манга'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('content', models.CharField(max_length=255, verbose_name='Текст')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anime', verbose_name='Аниме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
