# Generated by Django 3.2 on 2022-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220504_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='NSFW?'),
        ),
    ]
