# Generated by Django 3.2 on 2022-05-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
